language: node_js
node_js:
  - 10
install:
  - yarn install

script:
  - yarn build

before_deploy:
  - git add -f dist/build.js

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
