name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Lint commits
        run: yarn commitlint --verbose --from `git log -1 HEAD^1 --pretty=format:'%H'`
